apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ftpy-bstage
  annotations:
    github.com/project-slug: mumubstage/ftpy-bstage
    sonarqube.org/project-key: ftpy-backstage
    jenkins.io/github-folder: ftpy-backstage
spec:
  type: service
  lifecycle: production
  owner: adm-team
